Repository jenkins-x-plugins/jx-health, pull requests merged in 2021-01, with the labels that each got.

#14 refactor: move jx health get status to jx health status as it is a cleaner UX
  go.sum
  pkg/cmd/get/get.go
  pkg/cmd/root.go
  pkg/cmd/status/status.go
  pkg/cmd/status/status_test.go
  pkg/cmd/status/test_data/test-config
Labels: approved, size/M

#15 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/L, updatebot

#17 fix: rollback k8s upgrade
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#18 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: updatebot

#19 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/S, updatebot

#21 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/S, updatebot

#22 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: updatebot

#23 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/L, updatebot

#24 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/L, updatebot
